# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
api_platform:
    title: Hello API Platform
    description: 'Welcome to the Hello World API of APIs, powered by API Platform.'
    version: 1.0.0
    show_webby: false
    formats:
        jsonld: [ "application/ld+json" ]
        jsonhal: [ "application/hal+json" ]
        json: [ "application/json" ]
        xml: [ "application/xml", "text/xml" ]
        html: [ "text/html" ]
    error_formats:
        jsonproblem: [ "application/problem+json" ]
        jsonld: [ "application/ld+json" ] # Hydra error formats
        jsonapi: [ "application/vnd.api+json" ]

    # Swagger UI.
    enable_swagger_ui: true
    enable_swagger: true
    enable_entrypoint: false
    enable_docs: true
    enable_profiler: true

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
